### ISSUE TITLE
[Broadcaster] Audio/video desynchronization

### ISSUE THREAD

**Issue by mickel8** [elixir-webrtc/apps#34] opened 2024-07-25 09:13 UTC
Sometimes get audio/video desynchronization. Just ensure that both tracks are in the same stream on publisher, server and viewer sides.

**Comment by LVala** [comment] 2024-08-04 09:55
The tracks are properly assigned to the streams in the `admin/panel` player and the Broadcaster. As of now, I'm unable to reproduce the issue.

Reopen if the problems occur again.

**Closed by LVala** 2024-08-04 09:55 UTC
